JavaScript/CodingConventions.md
JS-Beautify is already formatting switch statements like this b/c of the `jslint_happy` flag that we have set to true. This will make our guidelines doc match JSLint.
=> Using JSLint whitespace conventions for switch statements.

PHP/CodingConventions.md
I believe many people follow line length limits at Wikia so it would be nice to formalize these a bit.  This pull request adds guidelines addressing two issues around long lines.  First how long a line should be in general and second what to do about long conditional statements specifically.
Note that this pull request is based on the "Reformat" branch.  Therefore this pull request is dependent on that branches pull request (https://github.com/Wikia/guidelines/pull/59).  This was done to separate these two changes and hopefully doesn't introduce more confusion.  If both pull requests are accepted, this pull request should be pulled first.
@Wikia/engineers
=> A proposal for line length limits in the PHP guidelines

PHP/CodingConventions.md, PHP/README.md
Update the PHP guideline directory to add some structure and make it easier to navigate when new guidelines are added.  This also makes the PHP directory more similar to the Python and Javascript directories.
=> Reorganize the PHP Guideline directory

APIDesign/README.md
This modification was inspired by https://wikia-inc.atlassian.net/browse/PLATFORM-607. Some of our mobile app clients rely upon the formatting of thumbnail URL in order to generate and display thumbnails that are appropriate for the device. This creates a coupling between the client and server which makes independent evolution of the server more difficult. That is, we can't change the thumbnail URLs without also changing the clients. We should try and avoid this situation in the future.
/cc @nmonterroso @aniaMu @pchojnacki
=> Add warning about client URI dependence

PHP/CodingConventions.md
This PR formalizes guidelines for PHP's alternate bracket array syntax. It seems to be a convention which was favored throughout the code base, but this adds it as an official Wikia convention. The confluence question raising whether this should be added as a convention and the responses that followed can be found [here](https://wikia-inc.atlassian.net/wiki/questions/19136541/coding-convention-for-bracket-array-syntax-in-php).
cc @Wikia/engineers
=> PHP bracket array syntax

JavaScript/CodingConventions.md
Our coding conventions ar emade to match JSLint, but our function convention
of a space between the name of a function and the left parenthesis throws an
error in JSLint:
Unexpected space between 'someFunc' and '('
So, switching to match JSLint by having no space between the function name and
the left parenthesis. This also matches Crockford's conventions on which JSLint
is based: http://javascript.crockford.com/code.html#function
/cc @lizlux
=> Make function whitespace convention match JSLint

githooks/pre-commit.d/php-10-syntax
This adds a php syntax check to the pre-commit hooks. It will run `php -l` on all files staged for commit and abort if the syntax check fails.
https://wikia-inc.atlassian.net/browse/PLATFORM-892
/cc @SebastianMarzjan @aniaMu
=> Add a php syntax check pre-commit hook

TypeScript/README.md
These rules would take some of the ambiguity out of formatting interfaces in typescript. 
Also fixed syntax errors in examples. 
@kenkouot @mklucsarits
=> Adding rules around interfaces

Java/README.md
Added information that it's not required to provide javadocs on all public elements, but only where they would make sense.
Pinging @cmiller-wikia @pchojnacki
=> Updated java comment standards

githooks/pre-commit
We ran into this issue when running git hooks while merging a branch with conflicts.  The best fix seems to be to just skip running the hooks at that point.   The "conflict" resolution code won't be checked but all the other code will have already been checked.  
https://github.com/brigade/overcommit/issues/52
=> skip commit hooks when merging or cherry-picking

JavaScript/CodingConventions.md
Currently we don't have a convention which it comes to setting context with `$.proxy()` or `.bind()`. Most of the time these 2 are synonymous, and without an official preference we end up with 2 ways of doing the same thing throughout our codebase. This PR hopes to clarify a preference for `.bind()`, since is native js rather than part of a library.
=> Add convention in js guidelines for using bind over proxy

JavaScript/CodingConventions.md
This bullet point was confusing to me when I read it, and I took "new line" to mean a blank line at the end of a file, when really what was meant was a new-line character at the end of a file. I wanted to make sure it was clear for others who read it in the future.
=> Clarify new-line character usage

TypeScript/README.md
The code snippet wasn't being displayed properly because of extra indentation
when not under a bullet point. Also, update the ToC for the current state of the doc.
=> Fix display of code snippet + update ToC

ConsulAndServiceDiscovery/README.md
This is a first pass at outlining guidelines for the use of consul and service registries at Wikia. This was prompted by our efforts to create a parallel but isolated development environment for services accessible via `services.wikia-dev.com`.
The rendered guideline can be viewed [here](https://github.com/Wikia/guidelines/tree/SERVICES-537/ConsulAndServiceDiscovery).
/cc @Wikia/services-team @cmiller-wikia @pchojnacki @frankfarmer @owend
=> Add consul and service discovery guidelines

Handlebars/README.md
We had this indentation rule at one point for mustache and I'd like to keep it around for handlebars. I think it makes the code easier to read.
=> Add indentation rule for HTML inside HB blocks

Services/ConsulAndServiceDiscovery.md
Production should never reference development and vice versa. Click [here](https://github.com/Wikia/guidelines/blob/strict-separation/Services/ConsulAndServiceDiscovery.md#service-registries) to see the rendered README.
/cc @wwarren
=> Add a note regarding cross environment references

JavaScript/CodingConventions.md
According to http://www.2ality.com/2013/07/trailing-commas.html
and http://rauschma.github.io/js-feature-matrix/
Trailing commas are allowed in ES5
and are only not working in IE < 8
Spec:
http://ecma262-5.com/ELS5_HTML.htm#Section_11.1.5
http://ecma262-5.com/ELS5_HTML.htm#Section_11.1.4
Our current support for IE says IE 11+
and traffic from IE < 8 is on level of 0.00% of all trafic
Reasoning:
1. smaller diffs in VCS
2. easier reorder of elements
=> Allow and encourage trailing commas

Process/PullRequests.md
After reviewing our pull request guidelines I think they cover most important topics. I added a small proposition for usage of tasks list in descriptions when that can help with readability. 
Also linked two great knowledge sources for PR and Code Review. 
/cc @Wikia/services-team
=> [SERVICES-1053] Additional guideline for PR description and knowledge sources

JavaScript/.eslintrc, JavaScript/CodingConventions.md
As a result of discussion around Mercury ESLint rules I'd like to propose changing indentation rules for `case` and `default` in `switch` statement.
The issue was put on Mercury TODOs list:
https://wikia-inc.atlassian.net/wiki/display/MER/Mercury+TODOs
Here is a PR for Mercury changing ESLint rules for entire mercury repo:
https://github.com/Wikia/mercury/pull/2048
=> Change switch case indent

JavaScript/CodingConventions.md
I wasn't sure if the whitespace guidelines apply to JSON, since it is not only used in JS. I've added a clause to make it explicit.
=> Whitespace guidelines also apply to JSON

JavaScript/es6Guidelines.md
We would like to try to scope variable declatation to only those code block that actually needs given variable. And in order to do that we propose small change in our ES6 guidelines - that you could use multiple `let` and `consts` inside any function. So code would change like this:
<table>
<tr><th>Before</th><th>After</th></tr>
<tr><td><pre>
function fooFunc() {
const foo = this.get('foo');
let bar;
if (foo === '123') {
bar = this.get('bar');
...
}
}
</pre></td><td><pre>
function fooFunc() {
const foo = this.get('foo');
if (foo === '123') {
const bar = this.get('bar');
...
}
}
</pre></td></tr>
</table>
Benefits of this change:
* Make code easier to read - lowering complexity of unnessesary variables
* Lower our technical debt - because that's one of the reasons why `const` and `let` were …
=> Allow multiple variable declarations

PHP/CodingConventions.md
I find it much easier to parse function calls with long-ish arguments when each argument is on a separate line. I think this is in keeping with what was already laid out, I just wanted to make it explicit.
=> Adding more examples for dealing with long lines

Java/README.md, Java/formatter/intellij-java-google-style-pre-14.1.xml, Java/formatter/intellij-java-google-style.xml
If you are importing more than a handful of classes from the same package, import the whole package. Masses of individual imports from a single package are just clutter and hide the intent of your code.
See also, five minutes into this video:  https://vimeo.com/105758303
I updated the default IDEA configs, but I don't don't believe in eclipse so someone else will have to fix that.
=> Allow wildcard imports

.gitmodules, PHP/CodingConventions.md
Looks like the url for the code-utils repo at `git.wikimedia.org` has moved to  `phabricator.wikimedia.org`.
The other steps in the [PHP Coding Conventions](https://github.com/Wikia/guidelines/blob/master/PHP/CodingConventions.md#tools) are still accurate and work with this change.
=> Update url for code-utils repo

Java/formatter/intellij-java-google-style.xml
In our .editorconfig we've got a limit of 120 characters, so developers using editor config plugin for IntelliJ may have had it overridden already.
Google has chosen our previous limit 100 as a compromise between 80 lines and 120.
I'd posit that while normally we keep lines fairly short, there are cases the 120 limit will be convenient.
`private static final String CONSTANT_WITH_NAME = "something almost fitting 120 chars"`
It also shouldn't be of much of an issue in case of vertical and Mac screens.
=> SER | Increase line width from 100 to 120 chars

.github/pull_request_template.md, Fandom Creator/README.md
The PR template actually works for the whole guidelines repo so I modified it a bit and moved it to the `.github` directory.
Also added some notes from the [code club doc](https://docs.google.com/document/d/1Yx5dzNhy8HZwMXD40Sco5kgEMKQaWn4b75wv6ImrL5c/edit) to the README. 
1/19/2019
@Wikia/cake
=> Updating PR template and FC guidelines README

Fandom Creator/JavaScript.md
* Enforces a MUST guideline to have all instance fields consistent with our binding guidelines. 
* Also added SHOULD to the imports guideline
* It's very common among react projects
* It's consistent with RDS
* The source code is shorter (no this and no super(props) (Small point)
* It's consistent with how we are binding functions
1/18/2018
@Wikia/cake
=> Instance Fields

Fandom Creator/JavaScript.md
We have been fairly inconsistent with propTypes. Sometimes they are found in the class itself, sometimes at the bottom of the file. The main advantage of this guideline is being able to quickly figure out what propTypes are required or passable as they will always be at the bottom.
The reason for choosing the bottom is because functional or return only components cannot define propTypes inside the class, whereas you can do so inside React.Components. By always listing them at the bottom there will be a consistent place to find propTypes (and defaultProps) regardless of the type of component or class.
18-01-2019
@Wikia/cake
=> Prop Types guidelines

PHP/bin/MediaWiki.xml
I'd like us to change our formatting to be more readable. The way MW codestyle splits newlines makes it pretty unreadable with fluent methods and constructors with multiple arguments.
The result of these changes can be seen in this PR:
https://github.com/Wikia/unified-platform/pull/450/files
=> SER | Adjust newlines in the MediaWiki code style
